### PR TITLE
Linux Makefiles + some minor stuff.

### PR DESCRIPTION
**Pull request by ehrenfeu**
I'm merging back the changes made during / after the 2014-11 developer's meeting even though the sports-renderer will be replaced (see OpenSeaMap/general#11) and @malcolmh is working on a new seamarks renderer (is there a repository somewhere?).

Parts of this are results from the discussion / work with @humbach during the meeting while trying to resurrect the "old" sports renderer and looking into the seamarks renderer.

We might also consider the changes made by some unknown (at least to me) user in [magwas/renderer/a3a9822](https://github.com/magwas/renderer/commit/a3a9822859bfe18667adbf9cd22b293a8d4edc15).

### CODE REVIEW

**Comment by malcolmh** [comment]
On 20 Jan 2015, at 12:52, Niko Ehrenfeuchter <notifications@github.com> wrote:
> 
> @malcolmh is working on a new seamarks renderer (is there a repository somewhere?)

http://svn.openstreetmap.org/applications/editors/josm/plugins/seachart/

It needs to be there as it is being developed initially as a JOSM plugin.=

**Comment by Skippern** [comment]
@malcolmh Will issues be handled through JOSM-trac as well, or should we have an issues-repo (without code)?

**Comment by ehrenfeu** [comment]
Thanks, @malcolmh!

Regarding JOSM, as you say "initially" - does it mean it is not a JOSM plugin anymore? Or does it still require JOSM to work, and if so, is there a way to run it headless?

Picking up on @Skippern's question, should we (me) maybe just set up a (read-only) github mirror of the SVN?

**Comment by malcolmh** [comment]
It will be both, and more! There will be a number of stand-alone apps that use the common class libraries (An example is "jicons"). The existing tile renderer will eventually be replaced by "jrender"

**Comment by malcolmh** [comment]
If a SVN repo can be mirrored in Git, then please go ahead!

**Comment by ehrenfeu** [comment]
Ok, I'll put this on my list. It's not hard, but you have to do it carefully, as there are a couple of pitfalls...

**Comment by ehrenfeu** [comment]
Here it is now: https://github.com/OpenSeaMap/seachart_renderer_next

I selected this name as @malcolmh said it will also be usable as a standalone app.

**Comment by ehrenfeu** [comment]
I should mention that the mirror is updated manually, there is no automatic link between the SVN repo and the one here on github. Feel free to bug me for documentation on how to do this!

**Comment by malcolmh** [comment]
Consider yourself bugged! I often update the SVN repo, so I do need to know how to sync this mirror.

**Comment by Skippern** [comment]
@malcolmh have you considered syncing svn and github in parallel? don't know if it is possible or if that would create some unforeseen actions?

**Comment by malcolmh** [comment]
Niko, I see that you did a refresh. Could you please instruct me on how to do this, so that I can keep the mirror up-to-date.

Aun, That may be an option, but I do not know the pros and cons of such a scheme.

**Comment by ehrenfeu** [comment]
@malcolmh: I did another update and will hopefully be able to give you meaningful instructions on how to do this...

**Pull request merged**
